version: '3.6'
services:
  postgres:
    image: "postgres:11-alpine"
    volumes:
    - "./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    - "./data/db:/var/lib/postgresql/data"
    restart: unless-stopped
  bot:
    build: "."
    ports:
    - "8993:8993"
    volumes:
    - "./:/app"
    restart: unless-stopped
