[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dogbot"
version = "0.0.0"
dependencies = []

[tool.pyright]
include = ["src"]
typeCheckingMode = "strict"
